### ISSUE TITLE
Can't use on RHEL6

### ISSUE THREAD

**Issue by grahamb** [ryankshaw/brandable_css#2]
This is more of an issue for pierreinglebert/node-zopfli, but it is impacting SFU's ability to build Canvas, so it's here as an FYI:

Asset compilation via brandable_css is no longer working on RedHat Enterprise Linux 6. The culprit is the node-zopfli module required by brandable_css, since 5f5b44a8597b7bc111c771686efade9a4045fb9f.

```
[webapps@atlassian canvas-lms]$  RAILS_ENV=production bundle exec rake canvas:compile_assets[false]

DEPRECATION WARNING: You have Rails 2.3-style plugins in vendor/plugins! Support for these plugins will be removed in Rails 4.0. Move them out and bundle them in your Gemfile, or fold them in to your app as lib/myplugin/* and config/initializers/myplugin.rb. See the release notes for more on this: http://weblog.rubyonrails.org/2012/1/4/rails-3-2-0-rc2-has-been-released. (called from <top (required)> at /tmp/canvas-lms/Rakefile:11)
--> Starting: 'Making sure node_modules are up to date'
--> Finished: 'Making sure node_modules are up to date' in 4.800319236
--> Starting: 'compile css (including custom brands)'
module.js:522
  var nodePath = process.env['NODE_PATH'];
                        ^
Error: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/canvas-lms/node_modules/brandable_css/node_modules/node-zopfli/lib/binding/node-v14-linux-x64/zopfli.node)
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/tmp/canvas-lms/node_modules/brandable_css/node_modules/node-zopfli/lib/zopfli.js:7:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/tmp/canvas-lms/node_modules/brandable_css/lib/handleGzip.js:11:37)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
--> Finished: 'compile css (including custom brands)' in 1.171742863
```

See: https://github.com/pierreinglebert/node-zopfli/issues/60

**Comment by grahamb** [comment]
The problem was a pre-built linux binary was being provided by node-zopfli; this binary was built on Ubuntu and didn't work on RHEL. The author has pulled the binary and all is now well.

**Comment by ryankshaw** [comment]
oh sweet, I was just going to start digging into this. I'm glad that worked
