### ISSUE TITLE
[CRITICAL] brandable_css/bin/brandable_css fails with new version of npm node-sass in Canvas LMS

### ISSUE THREAD

**Issue by Kulgar** [ryankshaw/brandable_css#3]
Hello Ryan, @ryankshaw 

Today I did an update of my npm modules in my Canvas LMS. 
But when I tried to launch brandable_css/bin/brandable_css, I got following error: 

``` bash
error compiling sass { [Error: Import directives may not be used within control directives or mixins.]
  cause: 
   { [Error: Import directives may not be used within control directives or mixins.]
     formatted: 'Error: Import directives may not be used within control directives or mixins.\n        on line 32 of app/stylesheets/base/_variables.scss\n>>   @import "brand_variables";\n   --^\n',
     message: 'Import directives may not be used within control directives or mixins.',
     column: 3,
     line: 32,
     file: 'app/stylesheets/base/_variables.scss',
     status: 1 },
  isOperational: true,
  formatted: 'Error: Import directives may not be used within control directives or mixins.\n        on line 32 of app/stylesheets/base/_variables.scss\n>>   @import "brand_variables";\n   --^\n',
  column: 3,
  line: 32,
  file: 'app/stylesheets/base/_variables.scss',
  status: 1 } Error: Import directives may not be used within control directives or mixins.
    at options.error (/home/regmillet/Workspace/RailsProjects/canvas-lms/node_modules/node-sass/lib/index.js:271:32) Import directives may not be used within control directives or mixins.
```

So, I tried to comment this line (my brand_variables file is empty) and got this new error: 

``` bash
error compiling sass { [Error: Undefined variable: "$lightBackground".]
  cause: 
   { [Error: Undefined variable: "$lightBackground".]
     formatted: 'Error: Undefined variable: "$lightBackground".\n        on line 5 of app/stylesheets/bundles/account_admin_tools.scss\n>>     background-color: $lightBackground;\n   ----------------------^\n',
     message: 'Undefined variable: "$lightBackground".',
     column: 23,
     line: 5,
     file: '/home/regmillet/Workspace/RailsProjects/canvas-lms/app/stylesheets/bundles/account_admin_tools.scss',
     status: 1 },
  isOperational: true,
  formatted: 'Error: Undefined variable: "$lightBackground".\n        on line 5 of app/stylesheets/bundles/account_admin_tools.scss\n>>     background-color: $lightBackground;\n   ----------------------^\n',
  column: 23,
  line: 5,
  file: '/home/regmillet/Workspace/RailsProjects/canvas-lms/app/stylesheets/bundles/account_admin_tools.scss',
  status: 1 } Error: Undefined variable: "$lightBackground".
    at options.error (/home/regmillet/Workspace/RailsProjects/canvas-lms/node_modules/node-sass/lib/index.js:271:32) Undefined variable: "$lightBackground".
```

I did some search and found that node-sass has been updated recently to version 3.5: https://github.com/sass/node-sass/commits/master

Take a look here: https://github.com/sass/node-sass/issues/1471 

As a temporary fix, I forced version 3.4 in my brandable_css package.json config, and it did solve the problem. 

Could you also do the same until you solve those breaking changes within Canvas? It may break a lot of production environments, don't you think? :)

**Comment by Kulgar** [comment]
I did not see you already did it in master ^^'

**Comment by ryankshaw** [comment]
Ya, it's fixed in master. Canvas master has a commit that depends on the new version
